apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.credentials.appSecretName }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/part-of: main-app
    app.kubernetes.io/component: database
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.global.database.user | quote }}
  password: {{ .Values.credentials.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.credentials.superuserSecretName }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/part-of: main-app
    app.kubernetes.io/component: database
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: {{ .Values.credentials.password | quote }}
