{{- if .Values.storageClass.create }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name }}
  labels:
    app.kubernetes.io/part-of: main-app
    app.kubernetes.io/component: storage
provisioner: {{ .Values.storageClass.provisioner }}
parameters:
  provisioningMode: {{ .Values.storageClass.provisioningMode }}
  fileSystemId: {{ .Values.storageClass.fileSystemId }}
  directoryPerms: {{ .Values.storageClass.directoryPerms | quote }}
  uid: {{ .Values.storageClass.uid | quote }}
  gid: {{ .Values.storageClass.gid | quote }}
  basePath: {{ .Values.storageClass.basePath | quote }}
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy }}
volumeBindingMode: {{ .Values.storageClass.volumeBindingMode }}
allowVolumeExpansion: {{ .Values.storageClass.allowVolumeExpansion }}
{{- end }}
