{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/part-of: main-app
    app.kubernetes.io/component: secret
type: Opaque
stringData:
  S3_BUCKET_NAME: {{ .Values.global.aws.s3BucketName | quote }}
  SNS_TOPIC_ARN: {{ .Values.global.aws.snsTopicArn | quote }}
  SECRET_KEY: {{ .Values.secret.secretKey | quote }}
{{- end }}
