apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.serviceAccount.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/part-of: main-app
    app.kubernetes.io/component: serviceaccount
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.global.serviceAccount.roleArn }}
