apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frontend.name" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "frontend.labels" . | nindent 8 }}
    spec:
      {{- if .Values.topologySpreadConstraints.enabled }}
      topologySpreadConstraints:
        - maxSkew: {{ .Values.topologySpreadConstraints.maxSkew }}
          topologyKey: {{ .Values.topologySpreadConstraints.topologyKey }}
          whenUnsatisfiable: {{ .Values.topologySpreadConstraints.whenUnsatisfiable }}
          labelSelector:
            matchLabels:
              {{- include "frontend.selectorLabels" . | nindent 14 }}
      {{- end }}
      containers:
        - name: {{ include "frontend.name" . }}
          image: {{ include "frontend.image" . }}
          imagePullPolicy: {{ include "frontend.pullPolicy" . }}
          ports:
            - containerPort: {{ .Values.containerPort }}
              name: http
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
