#!/usr/bin/env bash
# ============================================================================
# sync-values-from-tf.sh
# ----------------------------------------------------------------------------
# Reads outputs from the Terraform stack and writes values-from-tf.yaml, an
# override file that INJECTS every dynamic value into the main-app Helm chart.
# Nothing here patches raw YAML manifests and Terraform is never modified.
#
# Usage:
#   ./sync-values-from-tf.sh
#   helm upgrade --install ... -f main-app/values.yaml -f values-from-tf.yaml
# (deploy.sh does this automatically.)
# ============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
TF_DIR="${SCRIPT_DIR}/../terrform-deploy"
OUT_FILE="${SCRIPT_DIR}/values-from-tf.yaml"
NAMESPACE="main-app"

# ─────────────────────────────────────────────
# Guards
# ─────────────────────────────────────────────
for cmd in terraform aws kubectl; do
  command -v "$cmd" >/dev/null 2>&1 || { echo "ERROR: '$cmd' not found in PATH" >&2; exit 1; }
done
[[ -d "${TF_DIR}" ]] || { echo "ERROR: Terraform dir not found: ${TF_DIR}" >&2; exit 1; }

# ─────────────────────────────────────────────
# 1. Read Terraform outputs
# ─────────────────────────────────────────────
echo "[1/4] Reading Terraform outputs..."
AWS_REGION="$(terraform -chdir="${TF_DIR}" output -raw aws_region)"
CLUSTER_NAME="$(terraform -chdir="${TF_DIR}" output -raw eks_cluster_name)"
IRSA_ROLE_ARN="$(terraform -chdir="${TF_DIR}" output -raw irsa_role_arn)"
S3_BUCKET_NAME="$(terraform -chdir="${TF_DIR}" output -raw s3_bucket_name)"
SNS_TOPIC_ARN="$(terraform -chdir="${TF_DIR}" output -raw sns_topic_arn)"
EFS_FILESYSTEM_ID="$(terraform -chdir="${TF_DIR}" output -raw efs_filesystem_id)"

# ─────────────────────────────────────────────
# 2. Connect kubectl to the EKS cluster
# ─────────────────────────────────────────────
echo "[2/4] Updating kubeconfig for cluster '${CLUSTER_NAME}'..."
aws eks update-kubeconfig --region "${AWS_REGION}" --name "${CLUSTER_NAME}" --quiet 2>/dev/null || \
  aws eks update-kubeconfig --region "${AWS_REGION}" --name "${CLUSTER_NAME}"

# ─────────────────────────────────────────────
# 3. Resolve the app DB password (injected into Helm, not patched into YAML)
#    Priority: APP_DB_PASSWORD env var > live k8s secret > chart default.
# ─────────────────────────────────────────────
echo "[3/4] Resolving DB password..."
APP_DB_PASSWORD="${APP_DB_PASSWORD:-}"

if [[ -z "${APP_DB_PASSWORD}" ]]; then
  APP_DB_PASSWORD="$(kubectl get secret app-db-credentials -n "${NAMESPACE}" \
    -o jsonpath='{.data.password}' 2>/dev/null | base64 -d 2>/dev/null || true)"
fi

if [[ -n "${APP_DB_PASSWORD}" ]]; then
  echo "  Using existing DB password (from env/live secret)."
else
  echo "  No override found; keeping chart default DB password."
fi

# ─────────────────────────────────────────────
# 4. Write Helm override file (values-from-tf.yaml)
# ─────────────────────────────────────────────
echo "[4/4] Writing ${OUT_FILE}..."
{
  cat <<EOF
# AUTO-GENERATED by sync-values-from-tf.sh - do not edit by hand.
# Override values sourced from the Terraform stack, injected into the Helm chart.
global:
  serviceAccount:
    roleArn: ${IRSA_ROLE_ARN}
  aws:
    region: ${AWS_REGION}
    s3BucketName: ${S3_BUCKET_NAME}
    snsTopicArn: ${SNS_TOPIC_ARN}

database:
  storageClass:
    fileSystemId: ${EFS_FILESYSTEM_ID}
EOF
  if [[ -n "${APP_DB_PASSWORD}" ]]; then
    # Emit as a single-quoted YAML scalar (escape ' as '').
    yaml_pw="${APP_DB_PASSWORD//\'/\'\'}"
    printf "  credentials:\n    password: '%s'\n" "${yaml_pw}"
  fi
} > "${OUT_FILE}"

echo "Done. Cluster: ${CLUSTER_NAME} (${AWS_REGION})"
echo "Wrote ${OUT_FILE}"
echo "Deploy with:"
echo "  helm upgrade --install main-app ${SCRIPT_DIR}/main-app \\"
echo "    --namespace ${NAMESPACE} --create-namespace \\"
echo "    -f ${SCRIPT_DIR}/main-app/values.yaml -f ${OUT_FILE}"
